### ISSUE TITLE
Advice on building the project

### ISSUE THREAD

**Issue by EllingtonKirby** [ivanbravi/RinascimentoFramework#1]
Hello there, I am trying to build the framework myself but I am running into some issues building on Mac OS 12.5.1 device. Was wondering if you have any experience building the framework on a different machine.

**Comment by ivanbravi** [comment]
Hi @EllingtonKirby!

First of all, apologies for the late reply! 🙇‍♂️ 

I run it myself on Mac OS Monterey, so the following should work.
I suggest you to use [IntelliJ IDEA](https://www.jetbrains.com/idea/), it's fairly easy to set up.
You need to create a new Java project rooted at `$YOUR_PATH/RinascimentoFramework/`, make sure to setup `$YOUR_PATH/RinascimentoFramework/src/` as the source code folder and from the project structure window (you can find it in the menu `File/Project Structure…`) you can add all the libraries at path `$YOUR_PATH/RinascimentoFramework/lib/` at the `Project Settings/Libraries` tab.

Also, for the sake of completeness I use `openjdk-16 (16.0.2)` as Project SDK and Program Language Level `8`, however there are probably other legal configurations.

If you want to run the game with visuals there's a `main` point of access from the class `gui.ConsolePlayUI` , you can start understanding things from there.

I hope this was helpful.
Let me know if you have more questions.

**Comment by EllingtonKirby** [comment]
Hi @ivanbravi. Thank you so much for getting back to me!

The problem I have seems to be Mac OS specific in relation to the UI Library used in the project.

Specifically my error is
```
java.lang.NoClassDefFoundError: com/apple/eawt/QuitHandler
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3334)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3475)
	at java.base/java.lang.Class.getMethod0(Class.java:3461)
	at java.base/java.lang.Class.getMethod(Class.java:2193)
	at processing.core.PApplet.runSketch(PApplet.java:10707)
	at gui.ConsolePlayUI.main(ConsolePlayUI.java:98)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.QuitHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 7 more
```
Which occurs when I attempt to run the `ConsolePlayUI`

From my digging around, it appears to come from the `processing` library in `play.jar`. I think I would have to replace or modify that dependency (coming from this [stackoverflow](https://stackoverflow.com/questions/47343612/cannot-compile-when-importing-processing-library-into-eclipse) )

**Comment by ivanbravi** [comment]
@EllingtonKirby, sorry for the slow turnaround.
If in the future it takes me as long, it's probably because I've missed the GitHub email, feel free to ping me via email too, or send another message here ✌️ 

Sorry for the inconvenience, I haven't used the UI in a few years.

I've sorted out a few incompatibilities coming from Processing 3.
Make sure to download the latest commit then, instead of `openjdk-16 (16.0.2)`, download a JDK version 8, you can either use IntelliJ and automatically download one of the suggested ones (I used `corretto-1.8`) or you can download an Oracle distribution from their website (although some issues might arise).

It _should_ work fine then, if not, let me know and I'll see what I can do! 💪

**Comment by ivanbravi** [comment]
Also, I wanted to thank you very much for your interest in the project, you're being very helpful to help me find issues for first users that otherwise I wouldn't have time to go after. 👑

**Comment by ivanbravi** [comment]
**Heads up**
Since the last commit, I started using LFS due to some large dataset I added to the repo. Checkout the README for directions on how to use it. ✌️

**Comment by EllingtonKirby** [comment]
Thank you for all the assistance! I am just a bit distracted at the moment, will make sure to test these changes and hopefully try out some new algorithms on Splendor this summer

**Comment by EllingtonKirby** [comment]
Finally got around to building the project. 
The latest commit on your fork works for me. I had to add the `math3` and `org.jetbrains:annotations` modules as dependencies, but after that I am able to run the project. Thank you for your help!

**Comment by ivanbravi** [comment]
Brilliant! I'm glad it worked out.
Would you mind giving more info on what `add the math3 and org.jetbrains:annotations modules` entailed?
It would be great for future reference ✌️

**Comment by EllingtonKirby** [comment]
Hi there. So I just had to use the jetbrains add module interface (from the project structure window) to add those two modules. It might just be a matter of including references to them in the build scripts
